name: GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".gitignore"
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest  
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      HUGO_VERSION: latest
      HUGO_ENVIRONMENT: production
      # TZ: America/Los_Angeles
      REPO_OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name }}

    steps:
      - uses: actions/checkout@v4
        with:
          # submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - name: Setup Node
        uses: pnpm/action-setup@v4

      - run: pnpm install
      - run: hugo mod get -u && hugo mod tidy

      - name: Build Site
        run: |
          echo "${REPO_OWNER}"
          hugo --gc --minify --baseURL https://${REPO_OWNER}.github.io

      - name: Setup pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public

      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
